coverage:
  status:
    # measures overall project coverage
    project:
      default:
        threshold: 40% # how much decrease in coverage is needed to not consider success

    # measures PR or single commit coverage
    patch:
      default:
        threshold: 40% # how much decrease in coverage is needed to not consider success


    # project: off
    # patch: off
