_target_: src.models.phbreast_module.PHBreastLitModule

num_classes: 1
task: binary
lr: 0.00001
weight_decay: 0.0005
optimizer_type: adam
scheduler_type: null
net:
  _target_: src.models.components.hypercomplex_models.PHCResNet18
  channels: 2
  n: 2
  num_classes: ${..num_classes}
