name: Tests

on:
  # Runt test when pushing to main branch.
  push:
    branches: [main]
  # Run for any PRs.
  pull_request:

jobs:
  run_tests_code_coverage_ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: "3.10"

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt update && apt install -y libcurl4
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov[toml]
          pip install sh

      - name: List dependencies
        run: |
          python -m pip list

      - name: Run tests and collect coverage
        run: |
          wandb login --anonymously ${{ secrets.WANDB_TOKEN }}
          pytest --cov src

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true
